### PR TITLE
all-contributors

### PR DESCRIPTION
**Pull request by mia-riezebos**
Add `all-contributors`(`-cli`)

Also update README formatting slightly...

### CODE REVIEW

**Comment by mia-riezebos** [comment]
also addressed comments & thoughts from https://github.com/peterpeterparker/tsdoc-markdown/pull/13#issuecomment-1728135626

**Comment by peterpeterparker** [comment]
Super cool, thanks a lot!

**Comment by mia-riezebos** [comment]
it appears like the `"projectOwner"` key in [`.all-contributorsrc`](https://github.com/peterpeterparker/tsdoc-markdown/pull/15/commits/7a47d5c748479a1b8e670be0ee02455723624621#diff-cb22095514d0cab1f755ae3a7902f7d64d10199da210fbd1eb2b29eb758b38d2R3) needs to be your username, not your name!

**Comment by mia-riezebos** [comment]
> quick update: it appears like the `"projectOwner"` key in [`.all-contributorsrc`](https://github.com/peterpeterparker/tsdoc-markdown/pull/15/commits/7a47d5c748479a1b8e670be0ee02455723624621#diff-cb22095514d0cab1f755ae3a7902f7d64d10199da210fbd1eb2b29eb758b38d2R3) needs to be your username, not your name!
> 
> I think it's faster if you update it yourself, rather than going through another PR xd

after updating the key, you should run `npm run contributors:generate` to update all the links in the README.md

**Comment by peterpeterparker** [comment]
thanks for the quick update @mia-riezebos ! 

done #18

**Pull request merged**
